### ISSUE TITLE
Next() not working in middleware with this package

### ISSUE THREAD

**Issue by chris8447** [DanWebb/valid-shopify-request#9]
Hi Dan,
thanks for sharing this helpful package first of all. 

Currently I am building a Shopify App with the ShopifyCLI and I have run into a weird problem. Perhaps someone could have a look over it. Perhaps I'm blind.

**Problem**
Step 1: Koa-Router is expecting webhooks over this route
![Screenshot 2020-12-15 at 20 06 05](https://user-images.githubusercontent.com/36084535/102260623-fbb67f00-3f10-11eb-9704-23df61075513.png)

Step 2: Middleware
![Screenshot 2020-12-15 at 20 06 56](https://user-images.githubusercontent.com/36084535/102261130-89926a00-3f11-11eb-81ad-15df28767b74.png)

Step 3: Actual Handler
![Screenshot 2020-12-15 at 20 07 46](https://user-images.githubusercontent.com/36084535/102260898-3a4c3980-3f11-11eb-9f6f-27887be4342a.png)

However, next() is not being called when I use the `validShopifyRequest()` command. When I leave `validShopifyRequest()` out it's working without problems.

Has someone a clue?
Thanks in advance!

Chris

**Comment by DanWebb** [comment]
Hey @chris8447 I can't spot any issues looking at your code. So there's probably an error being swallowed somewhere within the call to validShopifyRequest.

The source code for this package isn't very big, you could copy the code from the src directory of this repo directly into your project temporarily. That way you could add logs and step through the code to see exactly where it stops and why.

**Comment by chris8447** [comment]
Hi @DanWebb,
thanks for taking the time to reply on this one. That's a good idea - I'll try that!
Chris

**Comment by chris8447** [comment]
Hi @DanWebb,
I copied the original source code into my project but no errors appear. I tried a different [package](https://github.com/dkershner6/verify-shopify-webhook#readme) and the same behavior is occuring.

I keep you updated.

**Comment by chris8447** [comment]
Hi Dan, I finally was able to recognize that the verification is doing it's job. The error is coming from somewhere else. That being said I am closing this issue. Thanks for your help! Chris
